### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by jonathan-richer** [aivis/user-stream#10]
@aivis Is this repository is still being worked on?

**Comment by alasdaircr** [comment]
`Latest commit 6eaa72e  on May 26, 2015`

Doesn't look like it.

**Comment by aivis** [comment]
@codeMeHtm It's not actively maintained and I don't have any plans for that.

https://www.npmjs.com/package/user-stream
```
9 downloads in the last day
35 downloads in the last week
209 downloads in the last month
```
