### ISSUE TITLE
I am getting HTTP statuscode 420 consistently 

### ISSUE THREAD

**Issue by samundrak** [aivis/user-stream#5]
While running an app i am getting 420 status code always and no any tweets is recieved how to overcome this?

**Comment by aivis** [comment]
According documentation **420** status code means "Enhance Your Calm" - "Returned by the version 1 Search and Trends APIs when you are being rate limited." (see https://dev.twitter.com/overview/api/response-codes) - not sure why it's being returned in your case.

Try to follow this example (probably it helps) - https://github.com/aivis/user-stream/blob/master/test/stream.js#L1
