### ISSUE TITLE
Fetch API cannot load https://userstream.twitter.com/1.1/user.json. Response for preflight has invalid HTTP status code 400

### ISSUE THREAD

**Issue by johnRivs** [aivis/user-stream#6]
I'm using Chrome. Installed the package via npm and used browserify.

I've followed the instructions and I always get `Fetch API cannot load https://userstream.twitter.com/1.1/user.json. Response for preflight has invalid HTTP status code 400` 

In fact, I've tried other packages and I get the same error. I can use curl from the command line to consume this endpoint, the one Twitter gives me from their OAuth signature generator. 

Also, right before that message, it shows `OPTIONS https://userstream.twitter.com/1.1/user.json`

Is it because I'm testing locally?

**Comment by aivis** [comment]
`Response for preflight has invalid HTTP status code 400`

You're getting CORS error - https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
- I'm not sure whether you should stream events directly to the Chrome browser because then you'll expose you're api keys... (try to use node.js)
